name: "Update Go Dependencies"
description: "Update one or more Go dependencies"
inputs:
  repos:
    description: "A comma or newline separated list of repositories to update, each with a specific version (e.g., 'github.com/anchore/stereoscope@main,github.com/anchore/syft@latest')"
    required: true

outputs:
  summary:
    description: "The changes detailing the version updates for each repository."
    value: ${{ steps.update-deps.outputs.summary }}
  draft:
    description: "Whether the PR should be marked as a draft."
    value: ${{ steps.update-deps.outputs.draft }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: 3.12
    - name: Update dependencies
      id: update-deps
      shell: bash
      run: |
        python .github/actions/update-go-dependencies/scripts/run.py
      env:
        INPUT_REPOS: ${{ inputs.repos }}
