name: "Binny"
description: "Install binny managed tools"
inputs:
  cache-key-prefix:
    description: "Prefix all cache keys with this value"
    required: true
    default: "181053ac82"

runs:
  using: "composite"
  steps:
    - name: Restore tool cache
      id: tool-cache
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: ${{ github.workspace }}/.tool
        key: ${{ inputs.cache-key-prefix }}-${{ runner.os }}-tool-${{ hashFiles('.binny.yaml') }}

    - name: Install project tools
      shell: bash
      run: |
        make tools
        .tool/binny list
        .tool/binny check
