# Description:
#   Automates handling of Dependabot pull requests by auto-approving them.
#   Only runs when the PR author is dependabot[bot].
#
# Reference:
#   https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request
#
# Permissions:
#   pull-requests: write  # to approve the PR
#
# Required Secrets:
#   None (uses automatic GITHUB_TOKEN)
#
# Usage Example:
#   jobs:
#     dependabot:
#       uses: anchore/workflows/.github/workflows/dependabot-automation.yaml@main


name: Dependabot Automation

on:
  # for checks in this repo (anchore/workflows)
  pull_request:

  # for use in external repos
  workflow_call:
    inputs:
      approve:
        default: true
        description: "Whether to auto-approve the PR"
        type: boolean

permissions:
  pull-requests: write

jobs:
  automation:
    # Runner definition: workflows/.github/runs-on.yml
    runs-on: runs-on=${{ github.run_id }}/runner=tiny
    # $ gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version 2022-11-28" /repos/anchore/syft/pulls/4638 | jq .user.login
    # "dependabot[bot]"
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@ffa630c65fa7e0ecfa0625b5ceda64399aea1b36 # v3.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Auto-approve PR
        if: inputs.approve == true
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
