# remove-awaiting-response-label.yaml
name: "Manage Awaiting Response Label"
on:
  workflow_call:
    inputs:
      users:
        # TODO: replace me with an org-based or team-based check
        default: '["wagoodman", "tgerla", "kzantow", "willmurphyscode", "spiffcs", "westonsteimel", "zhill", "nurmi", "popey"]'
        description: "JSON list as string of users to ignore"
        type: string

    secrets:
      token:
        description: "The classic GitHub token (with project access) to use for authentication"
        required: true

jobs:
  remove-awaiting-response:
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment'
    steps:
      - name: Show event info
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Number: ${{ github.event.issue.number }}"
          echo "Issue Author: ${{ github.event.issue.user.login }}"

      - name: Remove Awaiting Response Label
        if: |
          !contains(fromJson( inputs.users ), github.event.issue.user.login) && github.event.issue.user.login != ''
        run: |
          gh issue edit --repo ${{ github.event.repository.full_name }} ${{ github.event.issue.number }} --remove-label 'awaiting-response'
        env:
          GH_TOKEN: ${{ secrets.token }}
